version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:5.0
    container_name: mesmtf-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: mesmtf
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - mesmtf-network

  # Backend API
  backend:
    build: .
    container_name: mesmtf-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/mesmtf?authSource=admin
      JWT_SECRET: mesmtf-production-secret-key-2024
      JWT_EXPIRE: 7d
      JWT_REFRESH_SECRET: mesmtf-production-refresh-secret-key-2024
      JWT_REFRESH_EXPIRE: 30d
      HOSPITAL_NAME: Ministry of Health Hospital
      HOSPITAL_LOCATION: Windhoek, Namibia
      HOSPITAL_CONTACT_EMAIL: info@moh.gov
      HOSPITAL_CONTACT_PHONE: +264 61 123 4567
      HOSPITAL_EMERGENCY_CONTACT: +264 81 123 4567
      CORS_ORIGIN: http://localhost:3000
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    volumes:
      - ./uploads:/app/uploads
    networks:
      - mesmtf-network

  # MongoDB Express (Database Admin UI)
  mongo-express:
    image: mongo-express:latest
    container_name: mesmtf-mongo-express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    networks:
      - mesmtf-network

volumes:
  mongodb_data:

networks:
  mesmtf-network:
    driver: bridge
